# Generated by Django 5.2.15 on 2026-06-30 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='玉米重点品种数字展示平台', max_length=100, verbose_name='站点名称')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='公司名称')),
                ('logo', models.FileField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('hero_title', models.CharField(default='让每一块示范田，都有真实可见的成长记录', max_length=100, verbose_name='首页主标题')),
                ('hero_subtitle', models.TextField(default='聚焦重点玉米品种，连接田间表现、示范展示与客户服务。', validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='首页副标题')),
                ('primary_cta_label', models.CharField(default='查看示范点', max_length=30, verbose_name='主按钮文字')),
                ('secondary_cta_label', models.CharField(default='我要咨询', max_length=30, verbose_name='次按钮文字')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='客服电话')),
                ('footer_text', models.CharField(blank=True, max_length=200, verbose_name='页脚文字')),
                ('meta_description', models.CharField(default='玉米重点品种数字示范展示平台', max_length=160, verbose_name='页面描述')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
