# Generated by Django 5.2.15 on 2026-06-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_default_share_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='public_base_url',
            field=models.URLField(blank=True, help_text='生成二维码时使用，例如 https://show.example.com；为空时使用当前后台访问地址。', verbose_name='公开访问地址'),
        ),
    ]
