# Generated by Django 5.2.15 on 2026-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='amap_js_api_key',
            field=models.CharField(blank=True, help_text='在高德开放平台申请 Web 端（JS API）Key。', max_length=100, verbose_name='高德地图 JS API Key'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='amap_security_code',
            field=models.CharField(blank=True, help_text='高德 JS API 2.0 的 securityJsCode；正式环境建议改用服务端代理。', max_length=160, verbose_name='高德地图安全密钥'),
        ),
    ]
