# Generated by Django 5.2.15 on 2026-07-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_siteconfiguration_amap_js_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="color_theme",
            field=models.CharField(
                choices=[("system", "系统基本色调（绿色）"), ("purple_yellow", "紫色＋黄色")],
                default="purple_yellow",
                help_text="控制公开营销首页、示范传播页以及新生成的营销图片；不改变采集端和后台管理界面。",
                max_length=30,
                verbose_name="系统主色调",
            ),
        ),
    ]
