# Generated by Django 5.2.15 on 2026-07-11 16:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generated_user_phone(user_id):
    return f"199{int(user_id):08d}"


def create_profiles_for_existing_users(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model("core", "UserProfile")
    for user in User.objects.order_by("id"):
        UserProfile.objects.get_or_create(
            user_id=user.pk,
            defaults={"phone": generated_user_phone(user.pk)},
        )


def remove_generated_profiles(apps, schema_editor):
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.filter(phone__startswith="199").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siteconfiguration_color_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='必填。可用于登录系统，现有用户会先自动生成临时手机号，后续可修改。', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='请输入 11 位中国大陆手机号。', regex='^1[3-9]\\d{9}$')], verbose_name='手机')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, remove_generated_profiles),
    ]
