# Generated by Django 5.2.15 on 2026-06-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='品种名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL 标识')),
                ('positioning', models.CharField(blank=True, max_length=100, verbose_name='一句话定位')),
                ('summary', models.TextField(blank=True, verbose_name='品种简介')),
                ('approval_number', models.CharField(blank=True, max_length=100, verbose_name='审定编号')),
                ('suitable_area', models.TextField(blank=True, verbose_name='适宜区域')),
                ('maturity', models.CharField(blank=True, max_length=50, verbose_name='熟期')),
                ('plant_type', models.CharField(blank=True, max_length=50, verbose_name='株型')),
                ('ear_type', models.CharField(blank=True, max_length=50, verbose_name='穗型')),
                ('grain_type', models.CharField(blank=True, max_length=50, verbose_name='籽粒类型')),
                ('density_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='适宜密度下限（株/亩）')),
                ('density_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='适宜密度上限（株/亩）')),
                ('sowing_advice', models.TextField(blank=True, verbose_name='播期建议')),
                ('water_fertilizer_management', models.TextField(blank=True, verbose_name='水肥管理')),
                ('cultivation_points', models.TextField(blank=True, verbose_name='栽培要点')),
                ('risk_warning', models.TextField(blank=True, verbose_name='风险提示')),
                ('is_featured', models.BooleanField(default=True, verbose_name='首页推荐')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('internal_notes', models.TextField(blank=True, verbose_name='内部备注')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '品种',
                'verbose_name_plural': '品种',
                'ordering': ('sort_order', '-published_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('slug', models.SlugField(max_length=80, verbose_name='URL 标识')),
                ('point_type', models.CharField(choices=[('yield', '高产潜力'), ('lodging', '抗倒伏'), ('disease', '抗病性'), ('dehydration', '脱水快'), ('quality', '商品性'), ('other', '其他')], default='other', max_length=30, verbose_name='卖点类型')),
                ('short_description', models.CharField(blank=True, max_length=120, verbose_name='简短描述')),
                ('detail', models.TextField(blank=True, verbose_name='详细说明')),
                ('data_note', models.TextField(blank=True, verbose_name='数据说明')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('internal_basis', models.TextField(blank=True, verbose_name='内部依据')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_points', to='varieties.variety', verbose_name='所属品种')),
            ],
            options={
                'verbose_name': '核心卖点',
                'verbose_name_plural': '核心卖点',
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('variety', 'slug'), name='unique_selling_point_slug_per_variety')],
            },
        ),
    ]
