# Generated by Django 5.2.15 on 2026-06-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间')),
                ('path', models.CharField(db_index=True, max_length=300, verbose_name='页面路径')),
                ('source_code', models.CharField(db_index=True, default='direct', max_length=40, verbose_name='来源代码')),
                ('visitor_hash', models.CharField(db_index=True, max_length=64, verbose_name='匿名访客标识')),
            ],
            options={
                'verbose_name': '统计工作台',
                'verbose_name_plural': '统计工作台',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['occurred_at', 'source_code'], name='analytics_v_occurre_b2bfbf_idx')],
            },
        ),
    ]
