# Generated by Django 5.2.15 on 2026-07-01 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_demosite_latitude_demosite_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demosite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='高德地图 GCJ-02 纬度，例如 34.746600。', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='地图纬度'),
        ),
        migrations.AlterField(
            model_name='demosite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='高德地图 GCJ-02 经度，例如 113.625400。', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='地图经度'),
        ),
    ]
