# Generated by Django 5.2.15 on 2026-06-30 07:00

import django.core.validators
import django.db.models.deletion
import media_assets.models
import media_assets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='关联对象 ID')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('video_link', '视频链接')], max_length=20, verbose_name='媒体类型')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='说明')),
                ('alt_text', models.CharField(blank=True, max_length=160, verbose_name='替代文本')),
                ('image', models.ImageField(blank=True, upload_to=media_assets.models.media_upload_path, validators=[media_assets.validators.validate_image_upload], verbose_name='图片')),
                ('video_platform', models.CharField(blank=True, choices=[('douyin', '抖音'), ('wechat_channels', '微信视频号'), ('other', '其他')], max_length=30, verbose_name='视频平台')),
                ('video_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=('http', 'https'))], verbose_name='视频链接')),
                ('video_cover', models.ImageField(blank=True, upload_to=media_assets.models.media_upload_path, validators=[media_assets.validators.validate_image_upload], verbose_name='视频封面')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to=media_assets.models.thumbnail_upload_path, verbose_name='缩略图')),
                ('captured_at', models.DateField(blank=True, null=True, verbose_name='拍摄日期')),
                ('is_cover', models.BooleanField(default=False, verbose_name='设为封面')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('file_size', models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='文件大小')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='MIME 类型')),
                ('checksum_sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联类型')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '媒体素材',
                'verbose_name_plural': '媒体素材',
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['content_type', 'object_id', 'status'], name='media_asset_content_4229e5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('content_type', 'object_id'), name='one_cover_per_media_target')],
            },
        ),
    ]
