# Generated by Django 5.2.15 on 2026-06-30 16:27

import media_assets.models
import media_assets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='image',
            field=models.ImageField(blank=True, help_text='仅供“图片”类型使用；视频链接请将此字段留空。', upload_to=media_assets.models.media_upload_path, validators=[media_assets.validators.validate_image_upload], verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='video_cover',
            field=models.ImageField(blank=True, help_text='仅供“视频链接”类型使用；可上传 JPEG、PNG 或 WebP 封面图。', upload_to=media_assets.models.media_upload_path, validators=[media_assets.validators.validate_image_upload], verbose_name='视频封面'),
        ),
        migrations.AlterConstraint(
            model_name='mediaasset',
            name='one_cover_per_media_target',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('content_type', 'object_id'), name='one_cover_per_media_target', violation_error_message='同一品种、核心卖点或示范点只能设置一张封面；请取消其他媒体素材的“设为封面”后再保存。'),
        ),
    ]
