# Generated by Django 5.2.15 on 2026-06-30 18:10

import collection.models
import django.db.models.deletion
import media_assets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('sowing', '播种'), ('emergence', '出苗'), ('jointing', '拔节'), ('flowering', '抽雄吐丝'), ('filling', '灌浆'), ('maturity', '成熟'), ('harvest', '收获')], max_length=30, verbose_name='采集阶段')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交')], default='draft', max_length=20, verbose_name='状态')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='采集数据')),
                ('collector_note', models.TextField(blank=True, max_length=1000, verbose_name='负责人评价')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_observations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='sites.demosite', verbose_name='示范点')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_observations', to=settings.AUTH_USER_MODEL, verbose_name='最近修改人')),
            ],
            options={
                'verbose_name': '阶段采集记录',
                'verbose_name_plural': '阶段采集记录',
                'ordering': ('site', 'stage'),
            },
        ),
        migrations.CreateModel(
            name='CollectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交')], max_length=30, verbose_name='操作')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='collection.observation', verbose_name='采集记录')),
            ],
            options={
                'verbose_name': '采集操作历史',
                'verbose_name_plural': '采集操作历史',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ObservationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=collection.models.observation_photo_path, validators=[media_assets.validators.validate_image_upload], verbose_name='现场照片')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='照片说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='collection.observation', verbose_name='采集记录')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_photos', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '采集现场照片',
                'verbose_name_plural': '采集现场照片',
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('assigned_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collection_assignments', to=settings.AUTH_USER_MODEL, verbose_name='分配人')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_assignments', to='sites.demosite', verbose_name='示范点')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_site_assignments', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '负责人示范点分配',
                'verbose_name_plural': '负责人示范点分配',
                'ordering': ('site__province', 'site__name', 'user__username'),
            },
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('site', 'stage'), name='unique_observation_stage_site'),
        ),
        migrations.AddConstraint(
            model_name='siteassignment',
            constraint=models.UniqueConstraint(fields=('user', 'site'), name='unique_collector_site'),
        ),
    ]
