# Generated by Django 5.2.15 on 2026-07-01 03:15

import collection.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=collection.models.observation_video_path, validators=[collection.models.validate_field_video], verbose_name='现场视频')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='视频说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='collection.observation', verbose_name='采集记录')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_videos', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '采集现场视频',
                'verbose_name_plural': '采集现场视频',
                'ordering': ('uploaded_at',),
            },
        ),
    ]
