# Generated by Django 5.2.15 on 2026-07-01 03:51

import collection.models
import django.db.models.deletion
import media_assets.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_observationvideo'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionevent',
            name='action',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('regional_approved', '区域审核通过'), ('hq_approved', '总部审核通过'), ('published', '已公开'), ('rejected', '已退回')], max_length=30, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='collectionevent',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('regional_approved', '区域审核通过'), ('hq_approved', '总部审核通过'), ('published', '已公开'), ('rejected', '已退回')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='AnomalyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('sowing', '播种'), ('emergence', '出苗'), ('jointing', '拔节'), ('flowering', '抽雄吐丝'), ('filling', '灌浆'), ('maturity', '成熟'), ('harvest', '收获')], max_length=30, verbose_name='发生阶段')),
                ('anomaly_type', models.CharField(choices=[('missing', '缺苗'), ('pest', '虫害'), ('disease', '病害'), ('drought', '干旱'), ('waterlogging', '涝害'), ('lodging', '倒伏/倒折'), ('weather', '高温/风灾/冰雹'), ('management', '管理异常'), ('other', '其他')], max_length=30, verbose_name='异常类型')),
                ('severity', models.CharField(choices=[('low', '轻微'), ('medium', '中等'), ('high', '严重')], max_length=20, verbose_name='严重程度')),
                ('occurred_date', models.DateField(verbose_name='发生日期')),
                ('description', models.TextField(max_length=1000, verbose_name='情况说明')),
                ('suggested_action', models.TextField(blank=True, max_length=1000, verbose_name='建议措施')),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已处理')], default='open', max_length=20, verbose_name='处理状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上报时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_anomaly_reports', to=settings.AUTH_USER_MODEL, verbose_name='上报人')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_reports', to='sites.demosite', verbose_name='示范点')),
            ],
            options={
                'verbose_name': '田间异常上报',
                'verbose_name_plural': '田间异常上报',
                'ordering': ('-occurred_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='AnomalyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=collection.models.anomaly_photo_path, validators=[media_assets.validators.validate_image_upload], verbose_name='异常照片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomaly_photos', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='collection.anomalyreport', verbose_name='异常记录')),
            ],
            options={
                'verbose_name': '异常照片',
                'verbose_name_plural': '异常照片',
            },
        ),
        migrations.CreateModel(
            name='CollectionReviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('regional', '区域审核人'), ('headquarters', '总部审核人')], max_length=20, verbose_name='审核角色')),
                ('region', models.CharField(blank=True, choices=[('northeast', '东北'), ('huang_huai_hai', '黄淮海'), ('northwest', '西北'), ('southwest', '西南'), ('other', '其他')], help_text='区域审核人必须选择；总部审核人留空。', max_length=30, verbose_name='负责区域')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='审核账号')),
            ],
            options={
                'verbose_name': '采集审核人',
                'verbose_name_plural': '采集审核人',
            },
        ),
        migrations.CreateModel(
            name='PublishedObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='公开版本')),
                ('public_data', models.JSONField(default=dict, verbose_name='公开数据')),
                ('public_summary', models.TextField(blank=True, max_length=1000, verbose_name='公开摘要')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_versions', to='collection.observation', verbose_name='原始采集记录')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_observations', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '公开采集快照',
                'verbose_name_plural': '公开采集快照',
                'ordering': ('observation__site', 'observation__stage', '-version'),
                'constraints': [models.UniqueConstraint(fields=('observation', 'version'), name='unique_observation_public_version')],
            },
        ),
    ]
