# Generated by Django 5.2.15 on 2026-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_share_description',
            field=models.CharField(blank=True, help_text='为空时使用页面描述。', max_length=160, verbose_name='默认分享描述'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_share_image',
            field=models.ImageField(blank=True, help_text='建议使用 1.91:1 横图，例如 1200×630。', upload_to='site/share/', verbose_name='默认分享图'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_share_title',
            field=models.CharField(blank=True, help_text='为空时使用站点名称。', max_length=100, verbose_name='默认分享标题'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_notice',
            field=models.CharField(default='我同意平台保存以上信息，并由相关服务人员联系我。', max_length=300, verbose_name='咨询隐私说明'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_version',
            field=models.CharField(default='2026-07-01', max_length=30, verbose_name='隐私说明版本'),
        ),
    ]
