# Generated by Django 5.2.15 on 2026-06-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_public_base_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='操作')),
                ('object_type', models.CharField(blank=True, max_length=80, verbose_name='对象类型')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='对象 ID')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='发生时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '敏感操作审计',
                'verbose_name_plural': '敏感操作审计',
                'ordering': ('-created_at',),
            },
        ),
    ]
