RATING_CHOICES = (
    ("excellent", "优秀"),
    ("good", "良好"),
    ("average", "一般"),
    ("poor", "较差"),
)

CHOICE_SETS = {
    "rating": RATING_CHOICES,
    "sowing_method": (
        ("mechanical", "机械播种"),
        ("manual", "人工播种"),
        ("no_till", "免耕播种"),
        ("other", "其他"),
    ),
    "soil_moisture": (
        ("excellent", "充足"),
        ("suitable", "适宜"),
        ("dry", "偏干"),
        ("wet", "偏湿"),
    ),
    "leaf_color": (
        ("dark_green", "深绿"),
        ("green", "绿色正常"),
        ("light_green", "浅绿"),
        ("yellow", "发黄"),
        ("purple", "发紫"),
    ),
    "seedling_anomaly": (
        ("none", "无明显异常"),
        ("missing", "缺苗"),
        ("herbicide", "药害"),
        ("pest", "虫害"),
        ("drought", "干旱"),
        ("waterlogging", "涝害"),
    ),
    "plant_type": (
        ("compact", "紧凑"),
        ("semi_compact", "半紧凑"),
        ("loose", "平展"),
    ),
    "leaf_performance": (
        ("upright", "叶片上举"),
        ("normal", "叶片正常"),
        ("drooping", "叶片下垂"),
        ("rolled", "卷叶"),
        ("yellowing", "黄化"),
    ),
    "pest_disease": (
        ("none", "无明显病虫害"),
        ("leaf_spot", "叶斑类病害"),
        ("rust", "锈病"),
        ("stem_rot", "茎腐病"),
        ("ear_rot", "穗腐病"),
        ("borer", "玉米螟等虫害"),
        ("other", "其他"),
    ),
    "management": (
        ("none", "无新增管理"),
        ("fertilizing", "追肥"),
        ("irrigation", "浇水"),
        ("weeding", "除草"),
        ("pesticide", "病虫害防治"),
        ("chemical_control", "化控"),
    ),
    "tassel_size": (("large", "大"), ("medium", "中"), ("small", "小")),
    "pollen": (("abundant", "多"), ("normal", "正常"), ("low", "少")),
    "weather_stress": (
        ("none", "无明显影响"),
        ("heat", "高温"),
        ("drought", "干旱"),
        ("waterlogging", "涝害"),
        ("wind", "风灾"),
        ("hail", "冰雹"),
    ),
    "filling_progress": (
        ("fast", "快"),
        ("normal", "正常"),
        ("slow", "偏慢"),
    ),
    "ear_development": (
        ("excellent", "发育充分"),
        ("good", "发育良好"),
        ("average", "一般"),
        ("poor", "较差"),
    ),
    "dehydration": (
        ("fast", "快"),
        ("normal", "正常"),
        ("slow", "慢"),
    ),
    "harvest_method": (
        ("combine", "籽粒机收"),
        ("ear_machine", "果穗机收"),
        ("manual", "人工收获"),
        ("other", "其他"),
    ),
    "machine_performance": (
        ("smooth", "机收顺畅"),
        ("minor_breakage", "少量破碎"),
        ("major_breakage", "破碎较多"),
        ("minor_loss", "少量落粒"),
        ("major_loss", "落粒较多"),
        ("lodged_difficult", "倒伏影响机收"),
    ),
}

# name, label, field type, required when formally submitting
STAGE_FIELDS = {
    "sowing": [
        ("event_date", "播种日期", "date", True),
        ("method", "播种方式", "choice:sowing_method", True),
        ("density", "播种密度（株/亩）", "integer", True),
        ("row_spacing", "行距（厘米）", "decimal", True),
        ("plant_spacing", "自动计算株距（厘米）", "decimal", False),
        ("area_mu", "示范面积（亩）", "decimal", True),
        ("seed_batch", "种子批次（必要时填写）", "text", False),
        ("base_fertilizer", "底肥种类和用量（必要时填写）", "text", False),
        ("soil_moisture", "墒情", "choice:soil_moisture", True),
    ],
    "emergence": [
        ("event_date", "出苗日期", "date", True),
        ("emergence_rate", "出苗率（%）", "decimal", True),
        ("seedling_vigor", "苗势", "choice:rating", True),
        ("uniformity", "整齐度", "choice:rating", True),
        ("missing_level", "缺苗程度", "choice:rating", False),
        ("leaf_color", "叶色", "choice:leaf_color", True),
        ("anomaly", "异常情况（可多选）", "multi:seedling_anomaly", True),
    ],
    "jointing": [
        ("event_date", "拔节日期", "date", True),
        ("growth", "长势", "choice:rating", True),
        ("plant_type", "株型表现", "choice:plant_type", True),
        ("uniformity", "整齐度", "choice:rating", True),
        ("leaf_performance", "叶片表现", "choice:leaf_performance", True),
        ("pest_disease", "病虫害（可多选）", "multi:pest_disease", True),
        ("management", "田间管理措施（可多选）", "multi:management", True),
    ],
    "flowering": [
        ("tasseling_date", "抽雄日期", "date", True),
        ("silking_date", "吐丝日期", "date", True),
        ("coordination", "花期协调性", "choice:rating", True),
        ("tassel_size", "雄穗大小", "choice:tassel_size", True),
        ("pollen", "花粉量", "choice:pollen", True),
        ("silking_uniformity", "吐丝整齐度", "choice:rating", True),
        ("heat_drought", "气象影响（可多选）", "multi:weather_stress", True),
    ],
    "filling": [
        ("event_date", "调查日期", "date", True),
        ("filling_progress", "灌浆进度", "choice:filling_progress", True),
        ("stay_green", "保绿性", "choice:rating", True),
        ("plant_health", "植株健壮度", "choice:rating", True),
        ("ear_development", "穗部发育", "choice:ear_development", True),
        ("pest_disease", "病虫害（可多选）", "multi:pest_disease", True),
        ("stress", "抗逆表现（可多选）", "multi:weather_stress", True),
    ],
    "maturity": [
        ("event_date", "成熟日期", "date", True),
        ("plant_height", "株高（厘米）", "decimal", True),
        ("ear_height", "穗位（厘米）", "decimal", True),
        ("lodging_rate", "倒伏率（%）", "decimal", True),
        ("breakage_rate", "倒折率（%）", "decimal", False),
        ("barren_rate", "空秆率（%）", "decimal", False),
        ("ear_rot_rate", "穗腐率（%）", "decimal", False),
        ("stay_green", "保绿性", "choice:rating", True),
        ("dehydration", "脱水速度", "choice:dehydration", True),
        ("ear_quality", "果穗和籽粒商品性", "choice:rating", True),
    ],
    "harvest": [
        ("event_date", "收获日期", "date", True),
        ("method", "收获方式", "choice:harvest_method", True),
        ("actual_area", "实收面积（亩）", "decimal", True),
        ("actual_weight", "实收重量（公斤）", "decimal", True),
        ("moisture", "籽粒含水率（%）", "decimal", True),
        ("machine_performance", "机收表现（可多选）", "multi:machine_performance", True),
        ("commercial_quality", "商品性评价", "choice:rating", True),
    ],
}
