# Generated by Django 5.2.15 on 2026-06-30 15:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area_name', models.CharField(db_index=True, max_length=50, verbose_name='服务区域')),
                ('manager_name', models.CharField(max_length=50, verbose_name='联系人姓名')),
                ('role_title', models.CharField(default='区域经理', max_length=50, verbose_name='职位')),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]{7,30}$', '请输入正确的联系电话，可使用数字、空格、+、- 和括号。')], verbose_name='联系电话')),
                ('service_note', models.CharField(blank=True, max_length=160, verbose_name='服务说明')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '区域联系人',
                'verbose_name_plural': '区域联系人',
                'ordering': ('sort_order', 'area_name', 'manager_name'),
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]{7,30}$', '请输入正确的联系电话，可使用数字、空格、+、- 和括号。')], verbose_name='联系电话')),
                ('area_name', models.CharField(max_length=50, verbose_name='所在区域')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='单位/组织')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='咨询内容')),
                ('privacy_consent', models.BooleanField(default=False, verbose_name='已同意联系和信息处理')),
                ('status', models.CharField(choices=[('new', '待处理'), ('following', '跟进中'), ('completed', '已完成'), ('invalid', '无效线索')], db_index=True, default='new', max_length=20, verbose_name='处理状态')),
                ('admin_notes', models.TextField(blank=True, verbose_name='内部跟进记录')),
                ('source_path', models.CharField(blank=True, editable=False, max_length=300, verbose_name='来源页面')),
                ('followed_at', models.DateTimeField(blank=True, null=True, verbose_name='最近跟进时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('followed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='最近跟进人')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='inquiries.regionalcontact', verbose_name='分配给')),
            ],
            options={
                'verbose_name': '咨询记录',
                'verbose_name_plural': '咨询记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
