# Generated by Django 5.2.15 on 2026-06-30 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('sites', '0001_initial'),
        ('varieties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='consent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='同意时间'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='demo_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='sites.demosite', verbose_name='感兴趣示范点'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='intent_type',
            field=models.CharField(choices=[('consultation', '产品咨询'), ('site_visit', '预约看田'), ('trial', '申请试种'), ('agency', '代理合作')], db_index=True, default='consultation', max_length=30, verbose_name='意向类型'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='privacy_version',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='隐私说明版本'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='source_code',
            field=models.CharField(db_index=True, default='direct', editable=False, max_length=40, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9_-]{1,39}$', '来源代码只能包含小写字母、数字、下划线和连字符，长度为 2—40 位。')], verbose_name='来源代码'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='submission_key',
            field=models.CharField(blank=True, editable=False, max_length=36, verbose_name='防重复提交标识'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='varieties.variety', verbose_name='感兴趣品种'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(condition=models.Q(('submission_key', ''), _negated=True), fields=('submission_key',), name='unique_nonempty_inquiry_submission_key'),
        ),
    ]
