# Generated by Django 5.2.15 on 2026-06-30 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_consent_at_inquiry_demo_site_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', '待处理'), ('following', '跟进中'), ('completed', '已完成'), ('invalid', '无效线索')], max_length=20, verbose_name='处理状态')),
                ('note', models.TextField(max_length=1000, verbose_name='跟进记录')),
                ('next_action', models.CharField(blank=True, max_length=300, verbose_name='下一步计划')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_follow_ups', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='inquiries.inquiry', verbose_name='咨询记录')),
            ],
            options={
                'verbose_name': '线索跟进记录',
                'verbose_name_plural': '线索跟进记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
