# Generated by Django 5.2.15 on 2026-06-30 16:51

import media_assets.models
import media_assets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_alter_mediaasset_image_alter_mediaasset_video_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='video_checksum_sha256',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='视频 SHA-256'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='video_file',
            field=models.FileField(blank=True, help_text='仅供“本地视频”类型使用；最大 200 MB，建议使用 H.264 + AAC 编码。', upload_to=media_assets.models.video_upload_path, validators=[media_assets.validators.validate_mp4_upload], verbose_name='本地 MP4 视频'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='video_file_size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='视频文件大小'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='video_mime_type',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='视频 MIME 类型'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='image',
            field=models.ImageField(blank=True, help_text='仅供“图片”类型使用；视频类型请将此字段留空。', upload_to=media_assets.models.media_upload_path, validators=[media_assets.validators.validate_image_upload], verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('video_link', '视频链接'), ('local_video', '本地视频')], max_length=20, verbose_name='媒体类型'),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='video_cover',
            field=models.ImageField(blank=True, help_text='供“视频链接”或“本地视频”使用；可上传 JPEG、PNG 或 WebP 封面图。', upload_to=media_assets.models.media_upload_path, validators=[media_assets.validators.validate_image_upload], verbose_name='视频封面'),
        ),
    ]
