# Generated by Django 5.2.15 on 2026-06-30 17:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('varieties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='二维码名称')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='访问标识')),
                ('target_type', models.CharField(choices=[('home', '首页'), ('variety', '品种详情'), ('site', '示范点详情'), ('contact', '咨询表单')], max_length=20, verbose_name='目标类型')),
                ('source_code', models.CharField(help_text='例如 wechat_moments、douyin_profile、henan_field_sign。', max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9_-]{1,39}$', '来源代码只能包含小写字母、数字、下划线和连字符，长度为 2—40 位。')], verbose_name='来源代码')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='用途说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('scan_count', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='扫码次数')),
                ('last_scanned_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最近扫码时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_channel_qr_codes', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('demo_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_qr_codes', to='sites.demosite', verbose_name='目标示范点')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='channel_qr_codes', to='varieties.variety', verbose_name='目标品种')),
            ],
            options={
                'verbose_name': '渠道二维码',
                'verbose_name_plural': '渠道二维码',
                'ordering': ('-created_at',),
            },
        ),
    ]
