# Generated by Django 5.2.15 on 2026-07-09 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_marketing_publishing_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortVideoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='选题标题')),
                ('focus', models.CharField(max_length=80, verbose_name='单一重点')),
                ('script', models.TextField(max_length=1200, verbose_name='口播脚本')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('marketing_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_video_topics', to='campaigns.marketingpackage', verbose_name='营销素材包')),
            ],
            options={
                'verbose_name': '短视频选题',
                'verbose_name_plural': '短视频选题',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ExternalPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('wechat_moments', '微信朋友圈'), ('wechat_group', '微信群'), ('wechat_channels', '微信视频号'), ('douyin_video', '抖音短视频'), ('douyin_live', '抖音直播'), ('sales_share', '销售转发'), ('dealer_share', '经销商转发'), ('field_qrcode', '田间二维码')], max_length=40, verbose_name='发布渠道')),
                ('status', models.CharField(choices=[('draft', '待发布'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='发布状态')),
                ('title', models.CharField(max_length=160, verbose_name='发布标题')),
                ('account_name', models.CharField(blank=True, max_length=100, verbose_name='发布账号')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='外部链接')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name='播放/浏览量')),
                ('like_count', models.PositiveBigIntegerField(default=0, verbose_name='点赞量')),
                ('comment_count', models.PositiveBigIntegerField(default=0, verbose_name='评论量')),
                ('share_count', models.PositiveBigIntegerField(default=0, verbose_name='转发量')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_publications', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('marketing_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_publications', to='campaigns.marketingpackage', verbose_name='营销素材包')),
            ],
            options={
                'verbose_name': '外部发布记录',
                'verbose_name_plural': '外部发布记录',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['channel', 'status'], name='campaigns_e_channel_307a0c_idx'), models.Index(fields=['published_at'], name='campaigns_e_publish_5a4ecc_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketingWeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='开始日期')),
                ('end_date', models.DateField(db_index=True, verbose_name='结束日期')),
                ('title', models.CharField(max_length=160, verbose_name='周报标题')),
                ('summary', models.TextField(max_length=4000, verbose_name='周报摘要')),
                ('recommended_actions', models.TextField(blank=True, max_length=2000, verbose_name='建议动作')),
                ('is_archived', models.BooleanField(default=False, verbose_name='已归档')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_weekly_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '营销周报',
                'verbose_name_plural': '营销周报',
                'ordering': ('-start_date',),
                'constraints': [models.UniqueConstraint(fields=('start_date', 'end_date'), name='unique_weekly_report')],
            },
        ),
    ]
