# Generated by Django 5.2.15 on 2026-07-09 06:37

import campaigns.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_shortvideotopic_externalpublication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPosterVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(choices=[('moments', '朋友圈图文海报'), ('dealer', '经销商专属海报'), ('field_day', '观摩会/看田邀请'), ('weekly_recommendation', '本周重点推荐')], max_length=40, verbose_name='模板类型')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='公开标识')),
                ('title', models.CharField(max_length=120, verbose_name='海报标题')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='海报副标题')),
                ('call_to_action', models.CharField(default='扫码查看完整表现', max_length=80, verbose_name='行动提示')),
                ('image', models.ImageField(blank=True, upload_to=campaigns.models.marketing_poster_variant_path, verbose_name='海报图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('marketing_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_variants', to='campaigns.marketingpackage', verbose_name='营销素材包')),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_variants', to='campaigns.promotionidentity', verbose_name='专属推广人')),
                ('tracked_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poster_variants', to='campaigns.trackedlink', verbose_name='专属追踪链接')),
            ],
            options={
                'verbose_name': '营销海报模板',
                'verbose_name_plural': '营销海报模板',
                'ordering': ('variant_type', '-updated_at'),
            },
        ),
    ]
