# Generated by Django 5.2.15 on 2026-07-12 00:51

from django.db import migrations, models


def fill_wechat_moments_copy(apps, schema_editor):
    MarketingPackage = apps.get_model("campaigns", "MarketingPackage")
    for package in MarketingPackage.objects.select_related(
        "published_observation__observation__site__variety"
    ):
        if package.wechat_moments_copy:
            continue
        observation = package.published_observation.observation
        site = observation.site
        stage_label = observation.get_stage_display()
        tags = package.core_tags or []
        tag_copy = "｜".join(str(item) for item in tags[:3] if item)
        summary = (package.published_observation.public_summary or "").strip()
        copy_parts = [
            f"{site.variety.name}｜{site.name}{stage_label}表现更新",
            tag_copy,
            summary[:220],
            "扫码查看完整田间实拍，欢迎咨询和预约看田。",
        ]
        package.wechat_moments_copy = "\n".join(part for part in copy_parts if part)
        package.save(update_fields=("wechat_moments_copy",))


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_marketingpostervariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpackage',
            name='wechat_moments_copy',
            field=models.TextField(blank=True, max_length=1000, verbose_name='朋友圈文案'),
        ),
        migrations.RunPython(fill_wechat_moments_copy, migrations.RunPython.noop),
    ]
