# Generated by Django 5.2.15 on 2026-07-12 05:12

from django.db import migrations, models


def fill_customer_private_copy(apps, schema_editor):
    MarketingPackage = apps.get_model("campaigns", "MarketingPackage")
    for package in MarketingPackage.objects.select_related(
        "published_observation__observation__site__variety"
    ):
        if package.customer_private_copy:
            continue
        observation = package.published_observation.observation
        site = observation.site
        stage_label = observation.get_stage_display()
        tags = package.core_tags or []
        tag_copy = "、".join(str(item) for item in tags[:3] if item)
        summary = (package.published_observation.public_summary or "").strip()
        copy_parts = [
            f"您好，给您发一下{site.variety.name}在{site.name}的{stage_label}示范表现。",
            f"这一阶段重点可以先看：{tag_copy}。" if tag_copy else "",
            summary[:220],
            "您可以先打开链接看看田间实拍和阶段数据，如果想进一步了解、预约看田或试种，我再给您对接。",
        ]
        package.customer_private_copy = "\n".join(part for part in copy_parts if part)
        package.save(update_fields=("customer_private_copy",))


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_marketingpackage_wechat_moments_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpackage',
            name='customer_private_copy',
            field=models.TextField(blank=True, max_length=1000, verbose_name='客户私聊文案'),
        ),
        migrations.RunPython(fill_customer_private_copy, migrations.RunPython.noop),
    ]
