# Generated by Django 5.2.15 on 2026-07-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_marketingpackage_customer_private_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpublication',
            name='channel',
            field=models.CharField(choices=[('wechat_moments', '微信朋友圈'), ('wechat_group', '微信群'), ('wechat_channels', '微信视频号'), ('douyin_video', '抖音短视频'), ('douyin_live', '抖音直播'), ('field_qrcode', '田间二维码')], max_length=40, verbose_name='发布渠道'),
        ),
    ]
