# Generated by Django 5.2.15 on 2026-06-30 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('varieties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='示范点名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL 标识')),
                ('region', models.CharField(choices=[('northeast', '东北'), ('huang_huai_hai', '黄淮海'), ('northwest', '西北'), ('southwest', '西南'), ('other', '其他')], max_length=30, verbose_name='区域')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('county', models.CharField(max_length=50, verbose_name='区县')),
                ('township_village', models.CharField(blank=True, max_length=100, verbose_name='乡镇/村')),
                ('detailed_address', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('show_township', models.BooleanField(default=True, verbose_name='公开乡镇/村')),
                ('show_detailed_address', models.BooleanField(default=False, verbose_name='公开详细地址')),
                ('area_mu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='示范面积（亩）')),
                ('sowing_date', models.DateField(blank=True, null=True, verbose_name='播种日期')),
                ('planting_density', models.PositiveIntegerField(blank=True, null=True, verbose_name='种植密度（株/亩）')),
                ('planting_mode', models.CharField(blank=True, max_length=100, verbose_name='种植模式')),
                ('current_stage', models.CharField(blank=True, choices=[('sowing', '播种'), ('emergence', '出苗'), ('jointing', '拔节'), ('flowering', '抽雄吐丝'), ('filling', '灌浆'), ('maturity', '成熟'), ('harvest', '收获')], max_length=30, verbose_name='当前阶段')),
                ('main_performance', models.CharField(blank=True, max_length=120, verbose_name='主要表现')),
                ('description', models.TextField(blank=True, verbose_name='详细介绍')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('visiting_status', models.CharField(choices=[('not_open', '暂不开放'), ('open', '可预约看田'), ('closed', '已结束')], default='not_open', max_length=20, verbose_name='参观状态')),
                ('visiting_note', models.CharField(blank=True, max_length=200, verbose_name='预约提示')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('internal_owner', models.CharField(blank=True, max_length=100, verbose_name='内部负责人')),
                ('internal_notes', models.TextField(blank=True, verbose_name='内部备注')),
                ('published_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_sites', to='varieties.variety', verbose_name='所属品种')),
            ],
            options={
                'verbose_name': '示范点',
                'verbose_name_plural': '示范点',
                'ordering': ('sort_order', 'province', 'city', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('role_title', models.CharField(blank=True, max_length=50, verbose_name='职位/角色')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='覆盖区域')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '请输入正确的中国大陆手机号。')], verbose_name='手机号')),
                ('enterprise_wechat_note', models.CharField(blank=True, max_length=200, verbose_name='企业微信说明')),
                ('show_name', models.BooleanField(default=False, verbose_name='公开姓名')),
                ('show_phone', models.BooleanField(default=False, verbose_name='公开电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sites', models.ManyToManyField(blank=True, related_name='contacts', to='sites.demosite', verbose_name='关联示范点')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
