# Generated by Django 5.2.15 on 2026-07-01 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 纬度，例如 34.746600。', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='地图纬度'),
        ),
        migrations.AddField(
            model_name='demosite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS84 经度，例如 113.625400。', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='地图经度'),
        ),
    ]
