# Generated by Django 5.2.15 on 2026-07-01 07:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_collectionevent_action_and_more'),
        ('sites', '0003_alter_demosite_latitude_alter_demosite_longitude'),
        ('varieties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=50, verbose_name='申请人姓名')),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]{7,30}$', '请输入正确的联系电话。')], verbose_name='联系电话')),
                ('proposed_site_name', models.CharField(max_length=100, verbose_name='拟建示范点名称')),
                ('region', models.CharField(choices=[('northeast', '东北'), ('huang_huai_hai', '黄淮海'), ('northwest', '西北'), ('southwest', '西南'), ('other', '其他')], db_index=True, max_length=30, verbose_name='所属区域')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('county', models.CharField(max_length=50, verbose_name='区县')),
                ('township_village', models.CharField(blank=True, max_length=100, verbose_name='乡镇/村')),
                ('detailed_address', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('proposed_area_mu', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划示范面积（亩）')),
                ('planned_sowing_date', models.DateField(blank=True, null=True, verbose_name='计划播种日期')),
                ('planting_experience', models.CharField(choices=[('first', '首次开展示范'), ('one_to_three', '1—3 年'), ('over_three', '3 年以上')], max_length=30, verbose_name='示范经验')),
                ('request_note', models.TextField(blank=True, max_length=1000, verbose_name='申请说明')),
                ('status', models.CharField(choices=[('pending', '待区域审核'), ('approved', '已通过'), ('rejected', '已退回')], db_index=True, default='pending', max_length=20, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, max_length=1000, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人账号')),
                ('created_site', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_application', to='sites.demosite', verbose_name='创建的示范点')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_demo_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_applications', to='varieties.variety', verbose_name='申请示范品种')),
            ],
            options={
                'verbose_name': '示范申请',
                'verbose_name_plural': '示范申请',
                'ordering': ('-created_at',),
            },
        ),
    ]
