# Generated by Django 5.2.15 on 2026-07-01 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_demoapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demoapplication',
            name='login_username',
            field=models.CharField(blank=True, editable=False, max_length=150, verbose_name='登录用户名'),
        ),
        migrations.AlterField(
            model_name='demoapplication',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demo_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人账号'),
        ),
    ]
